---
title: 'Initial Analysis: Africa Data'
author: "Natalie Carlson"
date: "June 7, 2016"
output: pdf_document
---

# Distribution of Ratings

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)
library(matrixStats)
library(tm)
library(knitr)

setwd("/Users/nataliecarlson/Desktop/Tech Hubs/SSA Project Data and Analysis")

descriptions <- read.csv("descriptions.csv", header=TRUE, stringsAsFactors=FALSE)
descriptions <- descriptions[,-1]

master <- read.csv("SSA_Startups_4.csv", header=TRUE, stringsAsFactors=FALSE)

master <- master[-1,13:884]
master[master==2] <- 0
good_data <- filter(master, Q873_1=="" & Q873_2=="")
good_data <- as.data.frame(sapply(good_data, as.numeric))
good_data <- good_data[,1:870]
num_responses <- colSums(good_data!=0, na.rm=TRUE)
average_scores <- colMeans(good_data, na.rm=TRUE)
standard_devs <- colSds(as.matrix(good_data), na.rm=TRUE)

descriptions$average_score <- average_scores
descriptions$score_sd <- standard_devs
descriptions$num_responses <- num_responses
descriptions$funding_dummy <- ifelse(descriptions$total_funding>0,1,0)

funded_only <- filter(descriptions, funding_dummy==1)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
ggplot() + aes(average_scores) + geom_histogram(binwidth = 0.05) + scale_x_continuous(breaks = scales::pretty_breaks(n = 11), limits = c(-0.05, 1.05))
```


## Scatter by Funding


```{r echo=FALSE, message=FALSE, warning=FALSE}
ggplot(descriptions, aes(average_score, total_funding)) + geom_point()
```


## Funding Only Under $5m


```{r echo=FALSE, message=FALSE, warning=FALSE}
ggplot(funded_only, aes(average_score, total_funding)) + geom_point() + ylim(0,5000000)
```


## Funding Only Under $150k


```{r echo=FALSE, message=FALSE, warning=FALSE}
ggplot(funded_only, aes(average_score, total_funding)) + geom_point() + ylim(0,150000)
```


# LASSO: Coefficients Selected for Predicting mTurk Score


```{r echo=FALSE, message=FALSE, warning=FALSE, include=FALSE, results='hide'}
## Clean data and wordclouds
company_details <- descriptions$descriptions

# lowercase
company_details <- tolower(company_details)
company_details <- gsub("[\r\n]", " ", company_details)

# Replace @UserName
company_details <- gsub("@\\w+", " ", company_details)

# Remove punctuation
company_details <- gsub("[[:punct:]]+", " ", company_details)

# Remove digits
company_details <- gsub("[[:digit:]]+", " ", company_details)

# Remove links
company_details <- gsub("http\\w+", " ", company_details)

myStopwords <- c(stopwords("en"), "e", "s", "m", "d", "t", "africa", "african", "kenya", "kenyan", "nigeria", "nigerian", "uganda", "ugandan", "ghana", "ghanaian", "www", "com", "will", "can", "dazaar", "co", "propeies", "poal", "staups", "enteainment", "â", "propey")

# Remove Stopwords
company_details <- removeWords(company_details, myStopwords)

# Remove blank spaces at the beginning
company_details <- gsub("^ ", "", company_details)

# Remove blank spaces at the end
company_details <- gsub(" $", "", company_details)

# Remove tabs
company_details <- gsub("[ |\t]{2,}", " ", company_details)
company_details <- gsub("^ *|(?<= ) | *$", "", company_details, perl = TRUE)

## Wordclouds
descriptions$clean_text <- company_details


## Matching and adding in category information

#dealing with duplicates
descriptions$dup1 <- duplicated(descriptions[,1], fromLast = TRUE)
descriptions$dup2 <- duplicated(descriptions[,1], fromLast = FALSE)
#all_duplicates <- filter(descriptions, (dup1==TRUE | dup2==TRUE))
#all_duplicates <- all_duplicates[order(all_duplicates$descriptions),]
duplicates <- filter(descriptions, dup1==TRUE)
descriptions <- filter(descriptions, dup1==FALSE)
descriptions$match <- match(descriptions$descriptions, duplicates$descriptions, nomatch=0)
#average scores for dups
for (i in 1:nrow(descriptions)) {
  if (descriptions$dup2[i]==TRUE){
    n <- descriptions$match[i]
    count <- duplicates$num_responses[n] + descriptions$num_responses[i]
    descriptions$average_score[i] <- (duplicates$average_score[n] * (duplicates$num_responses[n]/count)) + (descriptions$average_score[i] * (descriptions$num_responses[i]/count))
    descriptions$num_responses[i] <- count
  }
}

#check <- filter(descriptions, dup2==TRUE)

#Add in categories
categories <- read.csv("category_matrix.csv", header=TRUE, stringsAsFactors=FALSE)
categories <- categories[,-1]
categories$descriptions <- NULL
descriptions_categories <- merge(descriptions, categories, by.x = c("names"), by.y=c("names"), all.x = TRUE, all.y = FALSE)
descriptions_categories$dup1 <- duplicated(descriptions_categories$descriptions, fromLast = TRUE)
descriptions_categories <- filter(descriptions_categories, dup1==FALSE)

## Regularized regression with just the text
library(quanteda)
dtm <- dfm(descriptions$descriptions, removePunct = TRUE)
dtm <- trim(dtm, minCount=5, minDoc=5)
dtm <- as.data.frame(dtm)
dtm$average_score <- descriptions$average_score
#dtm$funding_dummy <- descriptions$funding_dummy
#dtm$total_funding <- descriptions$total_funding

library(useful)
theForm <- average_score ~ .
#theForm <- funding_dummy ~ .
#theForm <- total_funding ~ .
masterX <- build.x(theForm, data=dtm)
masterY <- build.y(theForm, data=dtm)

library(glmnet)
set.seed(102)
glm1<-glmnet(x=masterX,y=masterY,alpha=1,family='gaussian')
cv.glm1 <- cv.glmnet(x=masterX,y=masterY,alpha=1,family='gaussian')
```



```{r echo=FALSE, message=FALSE, warning=FALSE}
plot(glm1, xvar="lambda", label=TRUE)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
plot(cv.glm1)
```


```{r echo=FALSE, message=FALSE, warning=FALSE, include=FALSE, results='hide'}
best_lambda <- cv.glm1$lambda.min
best_lambda
glm1<-glmnet(x=masterX,y=masterY,alpha=1,family='gaussian', lambda=best_lambda)
#coef(glm1)

#coefficient table
ind <- which(coef(glm1) != 0)
df <- data.frame(
    feature=rownames(coef(glm1))[ind],
    coefficient=coef(glm1)[ind]
  )
df <- df[order(df$coefficient),]
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
kable(df, row.names = FALSE)
```


## Including Industry and Country Dummies


```{r echo=FALSE, message=FALSE, warning=FALSE, include=FALSE, results='hide'}
## Do so with categories and countries included
dtm$country <- descriptions_categories$country
#dtm$funding_dummy <- descriptions$funding_dummy
#dtm$total_funding <- descriptions$total_funding
categories_only <- descriptions_categories[,13:224]
dtm <- cbind(dtm, categories_only)
dtm <- na.omit(dtm)

library(useful)
theForm <- average_score ~ .
#theForm <- funding_dummy ~ .
#theForm <- total_funding ~ .
masterX <- build.x(theForm, data=dtm)
masterY <- build.y(theForm, data=dtm)

library(glmnet)
set.seed(102)
glm1<-glmnet(x=masterX,y=masterY,alpha=1,family='gaussian')
cv.glm1 <- cv.glmnet(x=masterX,y=masterY,alpha=1,family='gaussian')
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
plot(glm1, xvar="lambda", label=TRUE)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
plot(cv.glm1)
```


```{r echo=FALSE, message=FALSE, warning=FALSE, include=FALSE, results='hide'}
best_lambda <- cv.glm1$lambda.min
best_lambda
glm1<-glmnet(x=masterX,y=masterY,alpha=1,family='gaussian', lambda=best_lambda)
#coef(glm1)

#coefficient table
ind <- which(coef(glm1) != 0)
df <- data.frame(
  feature=rownames(coef(glm1))[ind],
  coefficient=coef(glm1)[ind]
)
df <- df[order(df$coefficient),]
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
kable(df, row.names = FALSE)
```

# Simple Regressions on Funding

## Total Funding
```{r echo=FALSE, message=FALSE, warning=FALSE, include=FALSE, results='hide'}
drops <- c("total_funding","names", "descriptions", "wordcount", "score_sd", "num_responses", "clean_text", "dup1", "dup2", "match")
dummy_df<- descriptions_categories[ , !(names(descriptions_categories) %in% drops)]
drops <- c("funding_dummy","names", "descriptions", "wordcount", "score_sd", "num_responses", "clean_text", "dup1", "dup2", "match")
total_df <- descriptions_categories[ , !(names(descriptions_categories) %in% drops)]
lm1 <- lm(total_funding ~ average_score + country, total_df) 
lm2 <- lm(total_funding ~ average_score + I(average_score^2) + country, total_df)
lm3 <- lm(total_funding ~ average_score + ., total_df)
lm4 <- lm(total_funding ~ average_score + I(average_score^2) + ., total_df)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
kable(summary(lm1)$coef, digits=2)
kable(summary(lm2)$coef, digits=2)
```


## Limited to under $150k in funding (807 of 862 observations)


```{r echo=FALSE, message=FALSE, warning=FALSE, include=FALSE, results='hide'}
under_150k <- filter(total_df, total_funding<=150000)
lm1 <- lm(total_funding ~ average_score + country, under_150k) 
lm2 <- lm(total_funding ~ average_score + I(average_score^2) + country, under_150k)
lm3 <- lm(total_funding ~ average_score + ., under_150k) 
lm4 <- lm(total_funding ~ average_score + I(average_score^2) + ., under_150k)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
kable(summary(lm1)$coef, digits=2)
kable(summary(lm2)$coef, digits=2)
```

## Controlling for country and industry

```{r echo=FALSE, message=FALSE, warning=FALSE}
kable(summary(lm4)$coef, digits=2)
```